name: recipe_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  flutter_rating_bar: ^4.0.1
  flutter_lorem: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^3.0.1
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/intro.png
    - assets/images/avatar.png
    - assets/images/meals/1.png
    - assets/images/meals/2.png
    - assets/images/meals/3.png
    - assets/images/meals/4.png
    - assets/images/meals/5.png
    - assets/images/user_recipes/1.png
    - assets/images/user_recipes/2.png
    - assets/images/user_recipes/3.png
    - assets/images/user_recipes/4.png
    - assets/images/user_recipes/5.png
    - assets/images/search_result/1.png
    - assets/images/search_result/2.png
    - assets/images/search_result/3.png
    - assets/images/search_result/4.png
    - assets/images/user_photos/James Milner.png
    - assets/images/user_photos/Laura wilson.png
    - assets/images/user_photos/Lucas Moura.png
    - assets/images/user_photos/Isabella Ethan.png
    - assets/images/user_photos/Miquel Ferran.png
    - assets/images/ingridients/Tomatos.png
    - assets/images/ingridients/Cabbage.png
    - assets/images/ingridients/Taco.png
    - assets/images/ingridients/Slice Bread.png
    - assets/images/ingridients/Green Onion.png
    - assets/images/ingridients/Omelette.png
    - assets/images/ingridients/Hot Dog.png
    - assets/images/ingridients/Onion.png
    - assets/images/ingridients/Lettuce.png
    - assets/images/ingridients/Red & Green Chilli.png
    - assets/images/ingridients/Spinach.png
    - assets/images/ingridients/Fries.png
    - assets/images/ingridients/Chicken.png
    - assets/images/ingridients/Burger.png
    - assets/images/saved_recipes/1.png
    - assets/images/saved_recipes/2.png
    - assets/images/saved_recipes/3.png
    - assets/images/saved_recipes/4.png
    - assets/icons/chefshat.png
    - assets/icons/3dots.svg
    - assets/icons/arrow-right.svg
    - assets/icons/google_logo.svg
    - assets/icons/timer.svg
    - assets/icons/facebook_logo.svg
    - assets/icons/union.svg
    - assets/icons/home.svg
    - assets/icons/notification_bing.svg
    - assets/icons/profile.svg
    - assets/icons/favorite.svg
    - assets/icons/search.svg
    - assets/icons/setting.svg
    - assets/icons/notification_unread.svg
    - assets/icons/notification_read.svg

  uses-material-design: true

